// The project currently lacks React's JSX type declarations; keep this entry
// point compiling until the frontend dependencies are restored.
// @ts-nocheck

/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, {
  useState,
  useEffect,
  useCallback,
  useRef
} from 'react';

import { apiService } from './services/api';

import {
  SAMPLE_PERSON_RESULT,
  SAMPLE_COMPANY_RESULT
} from './services/sampleData';

import { Header } from './components/Header';
import { Hero } from './components/Hero';
import { UrlInput } from './components/UrlInput';
import { LoadingState } from './components/LoadingState';
import { ErrorMessage } from './components/ErrorMessage';
import { ResultSection } from './components/ResultSection';
import { HistoryModal } from './components/HistoryModal';
import { BackendSettingsModal } from './components/BackendSettingsModal';

import {
  EnrichmentResultItem,
  BackendConnectionStatus,
  HistoryRecord
} from './types';

import {
  Info,
  X
} from 'lucide-react';


export default function App() {

  // ============================================================
  // URL INPUT
  // ============================================================

  const [url, setUrl] =
    useState<string>('');


  // ============================================================
  // LOADING
  // ============================================================

  const [loading, setLoading] =
    useState<boolean>(false);


  // ============================================================
  // RESULT
  // ============================================================

  const [result, setResult] =
    useState<EnrichmentResultItem | null>(null);


  // ============================================================
  // RAW RESPONSE
  // ============================================================

  const [rawResponse, setRawResponse] =
    useState<any | null>(null);


  // ============================================================
  // ERROR
  // ============================================================

  const [error, setError] =
    useState<string | null>(null);


  // ============================================================
  // INFO MESSAGE
  // ============================================================

  const [infoMessage, setInfoMessage] =
    useState<string | null>(null);


  // ============================================================
  // FRONTEND ABORT CONTROLLER
  // ============================================================

  const abortControllerRef =
    useRef<AbortController | null>(null);


  // ============================================================
  // BACKEND REQUEST ID
  //
  // IMPORTANT:
  //
  // This is the ID generated by:
  //
  // /api/enrich/start
  //
  // The SAME ID is then sent to:
  //
  // /api/enrich
  //
  // And Stop uses:
  //
  // /api/enrich/stop/{request_id}
  // ============================================================

  const requestIdRef =
    useRef<string | null>(null);


  // ============================================================
  // MODALS
  // ============================================================

  const [isHistoryOpen, setIsHistoryOpen] =
    useState<boolean>(false);


  const [isSettingsOpen, setIsSettingsOpen] =
    useState<boolean>(false);


  // ============================================================
  // BACKEND STATUS
  // ============================================================

  const [backendStatus, setBackendStatus] =
    useState<BackendConnectionStatus>('checking');


  const [backendMessage, setBackendMessage] =
    useState<string>(
      'Testing connection...'
    );


  // ============================================================
  // HISTORY COUNT
  // ============================================================

  const [historyCount, setHistoryCount] =
    useState<number>(0);


  // ============================================================
  // REFRESH HISTORY COUNT
  // ============================================================

  const refreshHistoryCount =
    useCallback(() => {

      const list =
        apiService.getLocalHistory();

      setHistoryCount(
        list.length
      );

    }, []);


  // ============================================================
  // BACKEND HEALTH
  // ============================================================

  const checkHealth =
    useCallback(async () => {

      setBackendStatus(
        'checking'
      );

      try {

        const res =
          await apiService.checkBackendHealth();


        setBackendStatus(

          res.connected

            ? 'connected'

            : 'disconnected'

        );


        setBackendMessage(

          res.message ||

          (

            res.connected

              ? 'Backend Connected'

              : 'Backend Offline'

          )

        );

      }

      catch {

        setBackendStatus(
          'disconnected'
        );

        setBackendMessage(
          'Backend Offline'
        );

      }

    }, []);


  // ============================================================
  // INITIAL LOAD
  // ============================================================

  useEffect(() => {

    checkHealth();

    refreshHistoryCount();

  }, [
    checkHealth,
    refreshHistoryCount
  ]);


  // ============================================================
  // LINKEDIN URL VALIDATION
  // ============================================================

  const validateLinkedInUrl = (

    rawUrl: string

  ): {

    valid: boolean;

    errorMsg?: string;

  } => {


    const trimmed =
      rawUrl.trim();


    if (!trimmed) {

      return {

        valid: false,

        errorMsg:
          'Please enter a LinkedIn profile or company URL.'

      };

    }


    const linkedinRegex =
      /^(https?:\/\/)?(www\.)?linkedin\.com\/(in|company|school)\/[a-zA-Z0-9_\-\.\%]+/i;


    const generalLinkedinRegex =
      /^(https?:\/\/)?(www\.)?linkedin\.com\/.+/i;


    if (

      !generalLinkedinRegex.test(
        trimmed
      ) ||

      !linkedinRegex.test(
        trimmed
      )

    ) {

      return {

        valid: false,

        errorMsg:
          'Please enter a valid LinkedIn profile or company URL.'

      };

    }


    return {

      valid: true

    };

  };


  // ============================================================
  // EXTRACT URLS FROM TEXTAREA
  //
  // Supports:
  //
  // URL 1
  // URL 2
  // URL 3
  //
  // Also handles accidental blank lines.
  // ============================================================

  const getInputUrls =
    (): string[] => {

      return url

        .split(/\r?\n/)

        .map(
          item => item.trim()
        )

        .filter(
          item => item.length > 0
        );

    };


  // ============================================================
  // ENRICH
  // ============================================================

  const handleEnrich =
    async () => {


      // ========================================================
      // GET ALL URLS
      // ========================================================

      const urls =
        getInputUrls();


      console.log(
        '📋 URLs entered:',
        urls.length
      );


      // ========================================================
      // NO URL
      // ========================================================

      if (
        urls.length === 0
      ) {

        setError(
          'Please enter at least one LinkedIn URL.'
        );

        setInfoMessage(
          null
        );

        return;

      }


      // ========================================================
      // MAXIMUM
      //
      // We allow 100+.
      //
      // No artificial 100 limit here.
      // ========================================================

      if (
        urls.length > 1000
      ) {

        setError(
          'Please process a maximum of 1000 URLs at a time.'
        );

        setInfoMessage(
          null
        );

        return;

      }


      // ========================================================
      // VALIDATE EVERY URL
      // ========================================================

      const invalidUrls: string[] = [];


      for (
        const currentUrl of urls
      ) {

        const validation =
          validateLinkedInUrl(
            currentUrl
          );


        if (
          !validation.valid
        ) {

          invalidUrls.push(
            currentUrl
          );

        }

      }


      // ========================================================
      // INVALID URL FOUND
      // ========================================================

      if (
        invalidUrls.length > 0
      ) {

        setError(

          `Invalid LinkedIn URL found:\n${invalidUrls[0]}`

        );

        setInfoMessage(
          null
        );

        return;

      }


      // ========================================================
      // RESET UI
      // ========================================================

      setError(
        null
      );

      setInfoMessage(
        null
      );

      setResult(
        null
      );

      setRawResponse(
        null
      );


      // ========================================================
      // LOADING
      // ========================================================

      setLoading(
        true
      );


      // ========================================================
      // CLEAR OLD REQUEST ID
      // ========================================================

      requestIdRef.current =
        null;


      // ========================================================
      // CREATE FRONTEND ABORT CONTROLLER
      // ========================================================

      const controller =
        new AbortController();


      abortControllerRef.current =
        controller;


      try {


        // ======================================================
        // STEP 1
        //
        // CREATE REQUEST ID
        //
        // This MUST happen before /api/enrich.
        // ======================================================

        console.log(
          '🚀 Creating enrichment request...'
        );


        const startResponse =
          await apiService.startEnrichment();


        // ======================================================
        // CHECK ABORT
        // ======================================================

        if (
          controller.signal.aborted
        ) {

          return;

        }


        // ======================================================
        // SAVE REQUEST ID
        // ======================================================

        const requestId =
          startResponse.request_id;


        if (
          !requestId
        ) {

          throw new Error(
            'Backend did not return a request ID.'
          );

        }


        requestIdRef.current =
          requestId;


        console.log(
          '============================================'
        );

        console.log(
          '🚀 ENRICHMENT REQUEST CREATED'
        );

        console.log(
          'Request ID:',
          requestId
        );

        console.log(
          'Total URLs:',
          urls.length
        );

        console.log(
          '============================================'
        );


        // ======================================================
        // STEP 2
        //
        // SEND ALL URLS
        //
        // apiService now expects string[].
        // ======================================================

        const data =
          await apiService.enrichLinkedIn(

            urls,

            controller.signal,

            undefined,

            requestId

          );


        // ======================================================
        // CHECK ABORTED
        // ======================================================

        if (
          controller.signal.aborted
        ) {

          return;

        }


        // ======================================================
        // SAVE RAW RESPONSE
        // ======================================================

        setRawResponse(
          data
        );


        // ======================================================
        // BACKEND REQUEST ID
        // ======================================================

        if (

          data &&

          typeof data === 'object' &&

          'request_id' in data

        ) {

          requestIdRef.current =

            (data as any)
              .request_id ||

            requestId;

        }


        // ======================================================
        // RESULTS
        // ======================================================

        if (

          data?.results &&

          Array.isArray(
            data.results
          ) &&

          data.results.length > 0

        ) {


          // ====================================================
          // CHECK FAILED RESULTS
          // ====================================================

          const failedResults =
            data.results.filter(

              (item: any) =>

                item?.status === 'failed' ||

                item?.status === 'error'

            );


          // ====================================================
          // CHECK SUCCESS RESULTS
          // ====================================================

          const successfulResults =
            data.results.filter(

              (item: any) =>

                item?.status !== 'failed' &&

                item?.status !== 'error'

            );


          // ====================================================
          // ALL FAILED
          // ====================================================

          if (

            successfulResults.length === 0 &&

            failedResults.length > 0

          ) {

            setError(

              failedResults[0]?.error ||

              'All enrichment requests failed.'

            );

            setResult(
              null
            );

          }


          // ====================================================
          // SUCCESS
          //
          // Your existing ResultSection expects one item.
          //
          // For now we display the first successful result.
          //
          // ALL results are still preserved in rawResponse.
          // ====================================================

          else if (

            successfulResults.length > 0

          ) {

            setResult(

              successfulResults[0]

            );


            refreshHistoryCount();


            // ==================================================
            // INFO
            // ==================================================

            if (
              data.results.length > 1
            ) {

              setInfoMessage(

                `Completed ${successfulResults.length} of ${data.results.length} URLs.`

              );

            }

          }

        }


        // ======================================================
        // ALTERNATIVE RESPONSE FORMAT
        // ======================================================

        else if (

          data?.status === 'completed' &&

          (data as any)?.data

        ) {

          setResult(
            data as any
          );


          refreshHistoryCount();

        }


        // ======================================================
        // CANCELLED
        // ======================================================

        else if (

          data?.status === 'cancelled'

        ) {

          setInfoMessage(
            'Enrichment was stopped.'
          );

        }


        // ======================================================
        // NO DATA
        // ======================================================

        else {

          setError(
            'No enrichment data was returned.'
          );

        }


        // ======================================================
        // SUCCESSFUL COMPLETION
        //
        // Request ID no longer needed.
        // ======================================================

        if (

          data?.status === 'completed'

        ) {

          requestIdRef.current =
            null;

        }


      }

      catch (err: any) {


        // ======================================================
        // FRONTEND ABORT
        // ======================================================

        if (

          err?.name === 'AbortError' ||

          controller.signal.aborted

        ) {

          console.log(
            '🛑 Frontend enrichment request aborted.'
          );

          return;

        }


        // ======================================================
        // NORMAL ERROR
        // ======================================================

        console.error(
          '❌ Enrichment error:',
          err
        );


        setError(

          err?.message ||

          'The enrichment service returned an error.'

        );


        checkHealth();

      }


      finally {


        // ======================================================
        // CLEAN ABORT CONTROLLER
        // ======================================================

        if (

          abortControllerRef.current ===
          controller

        ) {

          abortControllerRef.current =
            null;

        }


        // ======================================================
        // STOP LOADING
        // ======================================================

        setLoading(
          false
        );

      }

    };


  // ============================================================
  // STOP ENRICHMENT
  //
  // IMPORTANT:
  //
  // Backend STOP is sent BEFORE frontend abort.
  //
  // This ensures FastAPI receives the request ID.
  // ============================================================

  const handleStop =
    async () => {


      console.log(
        '🛑 STOP BUTTON CLICKED'
      );


      // ========================================================
      // GET CURRENT REQUEST ID
      // ========================================================

      const requestId =
        requestIdRef.current;


      console.log(
        'Backend Request ID:',
        requestId
      );


      // ========================================================
      // STEP 1
      //
      // STOP BACKEND FIRST
      // ========================================================

      if (
        requestId
      ) {

        try {

          console.log(
            '🛑 Sending backend stop request...'
          );


          const response =
            await apiService.stopEnrichment(

              requestId

            );


          console.log(
            '✅ Backend stop response:',
            response
          );

        }

        catch (err) {

          console.error(
            '❌ Failed to send backend stop request:',
            err
          );

        }

      }

      else {

        console.warn(
          '⚠️ No backend request ID available.'
        );

      }


      // ========================================================
      // STEP 2
      //
      // ABORT FRONTEND FETCH
      // ========================================================

      if (
        abortControllerRef.current
      ) {

        console.log(
          '🛑 Aborting frontend request...'
        );


        abortControllerRef.current.abort();


        abortControllerRef.current =
          null;

      }


      // ========================================================
      // STEP 3
      //
      // RESET UI
      // ========================================================

      setLoading(
        false
      );


      setError(
        null
      );


      setInfoMessage(
        'Enrichment stopped.'
      );


      // ========================================================
      // CLEAR REQUEST ID
      // ========================================================

      requestIdRef.current =
        null;


      console.log(
        '🛑 Enrichment stopped.'
      );

    };


  // ============================================================
  // CLEAR
  // ============================================================

  const handleClear =
    () => {


      // ========================================================
      // FRONTEND ABORT
      // ========================================================

      if (
        abortControllerRef.current
      ) {

        abortControllerRef.current.abort();

        abortControllerRef.current =
          null;

      }


      // ========================================================
      // BACKEND STOP
      // ========================================================

      const requestId =
        requestIdRef.current;


      if (
        requestId
      ) {

        apiService
          .stopEnrichment(
            requestId
          )
          .catch(
            (err) => {

              console.error(
                'Failed to stop backend request:',
                err
              );

            }
          );

      }


      // ========================================================
      // CLEAR REQUEST ID
      // ========================================================

      requestIdRef.current =
        null;


      // ========================================================
      // RESET EVERYTHING
      // ========================================================

      setUrl('');

      setResult(
        null
      );

      setRawResponse(
        null
      );

      setError(
        null
      );

      setInfoMessage(
        null
      );

      setLoading(
        false
      );

    };


  // ============================================================
  // SAMPLE DATA
  // ============================================================

  const handleLoadSample = (

    type:
      'person' |
      'company'

  ) => {


    if (
      loading
    ) {

      handleStop();

    }


    const sample =

      type === 'person'

        ? SAMPLE_PERSON_RESULT

        : SAMPLE_COMPANY_RESULT;


    setUrl(
      sample.url || ''
    );


    setResult(
      sample
    );


    setRawResponse({

      status:
        'completed',

      count:
        1,

      results:
        [sample]

    });


    setError(
      null
    );


    setInfoMessage(
      null
    );


    setLoading(
      false
    );


    requestIdRef.current =
      null;

  };


  // ============================================================
  // HISTORY
  // ============================================================

  const handleSelectHistoryRecord = (

    record: HistoryRecord

  ) => {


    if (
      loading
    ) {

      handleStop();

    }


    setUrl(
      record.url
    );


    setResult(
      record.response
    );


    setRawResponse({

      status:
        'completed',

      count:
        1,

      results:
        [record.response]

    });


    setError(
      null
    );


    setInfoMessage(
      null
    );


    requestIdRef.current =
      null;

  };


  // ============================================================
  // UI
  // ============================================================

  return (

    <div className="min-h-screen bg-[#020617] text-slate-200 font-sans flex flex-col selection:bg-blue-500/30 selection:text-blue-200 relative overflow-x-hidden">


      {/* ======================================================
          BACKGROUND
      ====================================================== */}

      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">

        <div className="absolute top-[-10%] left-[-10%] w-[45%] h-[45%] rounded-full bg-blue-900/20 blur-[120px]" />

        <div className="absolute bottom-[-10%] right-[-10%] w-[45%] h-[45%] rounded-full bg-indigo-900/20 blur-[120px]" />


        <div

          className="absolute inset-0 opacity-[0.025]"

          style={{

            backgroundImage:
              `radial-gradient(rgba(255, 255, 255, 0.4) 1px, transparent 1px)`,

            backgroundSize:
              '32px 32px'

          }}

        />

      </div>


      {/* ======================================================
          MAIN APP
      ====================================================== */}

      <div className="relative z-10 flex flex-col flex-1">


        {/* ====================================================
            HEADER
        ==================================================== */}

        <Header

          backendStatus={
            backendStatus
          }

          backendMessage={
            backendMessage
          }

          onOpenHistory={() =>
            setIsHistoryOpen(true)
          }

          onOpenSettings={() =>
            setIsSettingsOpen(true)
          }

          onCheckHealth={
            checkHealth
          }

          onLoadSample={
            handleLoadSample
          }

          historyCount={
            historyCount
          }

        />


        {/* ====================================================
            MAIN
        ==================================================== */}

        <main className="flex-1 pb-20">


          {/* HERO */}

          <Hero />


          {/* ==================================================
              URL INPUT
          ================================================== */}

          <UrlInput

            url={
              url
            }

            setUrl={

              (newUrl) => {

                setUrl(
                  newUrl
                );


                if (
                  error
                ) {

                  setError(
                    null
                  );

                }


                if (
                  infoMessage
                ) {

                  setInfoMessage(
                    null
                  );

                }

              }

            }

            onEnrich={
              handleEnrich
            }

            onStop={
              handleStop
            }

            onClear={
              handleClear
            }

            onOpenHistory={() =>
              setIsHistoryOpen(true)
            }

            loading={
              loading
            }

          />


          {/* ==================================================
              INFO MESSAGE
          ================================================== */}

          {infoMessage &&
            !loading && (

            <div className="w-full max-w-3xl mx-auto px-4 mt-3 animate-in fade-in slide-in-from-top-1 duration-200">

              <div className="p-3.5 rounded-xl bg-blue-500/10 border border-blue-500/20 backdrop-blur-md flex items-center justify-between gap-3 text-xs text-blue-300">


                <div className="flex items-center gap-2.5">

                  <Info className="w-4 h-4 text-blue-400 flex-shrink-0" />

                  <span>
                    {infoMessage}
                  </span>

                </div>


                <button

                  type="button"

                  onClick={() =>
                    setInfoMessage(
                      null
                    )
                  }

                  className="text-blue-400/70 hover:text-blue-200 p-1 transition-colors"

                >

                  <X className="w-3.5 h-3.5" />

                </button>

              </div>

            </div>

          )}


          {/* ==================================================
              ERROR
          ================================================== */}

          {error && (

            <ErrorMessage

              message={
                error
              }

            />

          )}


          {/* ==================================================
              LOADING
          ================================================== */}

          {loading && (

            <LoadingState

              onStop={
                handleStop
              }

            />

          )}


          {/* ==================================================
              RESULT
          ================================================== */}

          {result &&
            !loading && (

            <ResultSection

              result={
                result
              }

              rawResponse={
                rawResponse
              }

            />

          )}

        </main>


        {/* ======================================================
            FOOTER
        ====================================================== */}

        <footer className="border-t border-white/5 bg-slate-950/40 backdrop-blur-md py-4 px-6 sm:px-8 mt-auto">

          <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-400">


            <div className="flex flex-wrap items-center justify-center sm:justify-start gap-2">

              <span className="font-bold text-white tracking-wider">
                LABELNEST
              </span>

              <span className="text-slate-600">
                •
              </span>

              <span className="text-slate-300 font-medium">
                LinkedIn Intelligence Platform
              </span>

            </div>


            <div className="text-xs text-slate-500">
              Powered by Mindcase & Sarvam AI
            </div>


          </div>

        </footer>


      </div>


      {/* ======================================================
          HISTORY MODAL
      ====================================================== */}

      <HistoryModal

        isOpen={
          isHistoryOpen
        }

        onClose={() =>
          setIsHistoryOpen(false)
        }

        onSelectRecord={
          handleSelectHistoryRecord
        }

      />


      {/* ======================================================
          BACKEND SETTINGS
      ====================================================== */}

      <BackendSettingsModal

        isOpen={
          isSettingsOpen
        }

        onClose={() =>
          setIsSettingsOpen(false)
        }

        onSaved={
          checkHealth
        }

      />

    </div>

  );

}